version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5212:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - weather-network

  blazorui:
    build:
      context: .
      dockerfile: ./BlazorUI/Dockerfile.compose
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "BackendApi__BaseUrl=http://backend:8080"
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge